---
- name: checkup on windows
  hosts: windows
  connection: winrm
  gather_facts: true
  
  tasks:
    - name: assert the domain
      ansible.builtin.assert:
        that: 
          -  ansible_facts.processor_cores >= 1
          -  ansible_facts.architecture == "64-bit"
          -  ansible_facts.fqdn == "vagrant"

        fail_msg: "Not configured properly"
        success_msg: "Ready to go"


