---
- name: copy file to a windows machine
  hosts: windows
  gather_facts: false
  #connection: winrm    # defined in inventory

  tasks:
  - name: move file to student user desktop
    ansible.windows.win_copy:
      src: ~/mycode/alta3.txt
      dest: "C:\\Users\\{{ ansible_user }}\\Desktop\\alta3.txt"
  
  # SOLUTION 01
  - name: move file from desktop to desktop
    ansible.windows.win_copy:
      remote_src: true
      src: "C:\\Users\\{{ ansible_user }}\\Desktop\\alta3.txt"
      dest: "C:\\Users\\{{ ansible_user }}\\Desktop\\alta3_second_copy.txt"
